### ISSUE TITLE
Can't install with eslint 9.x

### ISSUE THREAD

**Issue by robtaylor** [un-ts/eslint-plugin-import-x#124] opened 2024-08-06 13:59 UTC
currently getting:
```
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @typescript-eslint/utils@7.18.0
npm warn Found: eslint@9.8.0
npm warn node_modules/eslint
npm warn   peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm warn   node_modules/eslint-plugin-import
npm warn     peer eslint-plugin-import@"*" from eslint-import-resolver-typescript@3.6.1
npm warn     node_modules/eslint-import-resolver-typescript
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^8.56.0" from @typescript-eslint/utils@7.18.0
npm warn node_modules/eslint-plugin-import-x/node_modules/@typescript-eslint/utils
npm warn   @typescript-eslint/utils@"^7.4.0" from eslint-plugin-import-x@3.1.0
npm warn   node_modules/eslint-plugin-import-x
npm warn
npm warn Conflicting peer dependency: eslint@8.57.0
npm warn node_modules/eslint
npm warn   peer eslint@"^8.56.0" from @typescript-eslint/utils@7.18.0
npm warn   node_modules/eslint-plugin-import-x/node_modules/@typescript-eslint/utils
npm warn     @typescript-eslint/utils@"^7.4.0" from eslint-plugin-import-x@3.1.0
```

I think the fix is to bump @typescript-eslint/utils to ^8.0.1

**Comment by controversial** [comment] 2024-08-06 23:18
duplicate of #121

**Comment by SukkaW** [comment] 2024-08-26 21:36
`eslint-plugin-import-x@4.0.0` is now released with peerDeps of `@typescript-eslint/utils` bumps to 8.

**Closed by SukkaW** 2024-08-26 21:36 UTC
